"""add user-generated file model

Revision ID: 93f130ea6c4c
Revises: b8f6bf964fec
Create Date: 2022-09-26 09:57:37.491025

"""
import depot
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

from apollo.users.models import UserFileType

# revision identifiers, used by Alembic.
revision = "93f130ea6c4c"
down_revision = "b8f6bf964fec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column(
            "content",
            depot.fields.sqlalchemy.UploadedFileField(
                upload_storage="generated_files"
            ),
            nullable=True,
        ),
        sa.Column(
            "file_type",
            sqlalchemy_utils.types.choice.ChoiceType(
                UserFileType, impl=sa.Integer()
            ),
            nullable=False,
        ),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_file")
    # ### end Alembic commands ###
