"""add unique constraint on participant table

Revision ID: c26f1da31495
Revises: c4166678fb79
Create Date: 2022-01-13 11:05:51.734354

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c26f1da31495"
down_revision = "c4166678fb79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "participant", ["participant_set_id", "email"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "participant", type_="unique")
    # ### end Alembic commands ###
