"""add is_trashed column

Revision ID: e725ce7466df
Revises: c4166678fb79
Create Date: 2022-03-06 02:07:07.685764

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e725ce7466df"
down_revision = "c4166678fb79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event", sa.Column("is_trashed", sa.Boolean(), nullable=True)
    )
    op.add_column("form", sa.Column("is_trashed", sa.Boolean(), nullable=True))
    op.add_column(
        "location_set", sa.Column("is_trashed", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "participant_set", sa.Column("is_trashed", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participant_set", "is_trashed")
    op.drop_column("location_set", "is_trashed")
    op.drop_column("form", "is_trashed")
    op.drop_column("event", "is_trashed")
    # ### end Alembic commands ###
